version: 0.0
os: windows
files:
  - source: \sem3Cloud\*
    destination: /home/ec2-user/test
  - source: \sem3Cloud.sln
    destination: /home/ec2-user/test
  
hooks:
  BeforeInstall:
    - location: \deletewebsite.bat
      timeout: 180
  AfterInstall:
    - location: \installwebsite.bat
      timeout: 180