version: 0.0
os: linux
files:
  - source: /sem3Cloud/
    destination: /var/www/dscc_4047
  - source: scripts/dscc_4047.conf
    destination: /etc/httpd/conf.d/
  - source: scripts/dscc_4047.service
    destination: /etc/systemd/system/

hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
    
